#!/bin/bash

# Get metadata
TITLE=$(banshee-1 --query-title)
ARTIST=$(banshee-1 --query-artist)
ALBUM=$(banshee-1 --query-album)

# Strip off headings
TITLE=${TITLE#*: }
ARTIST=${ARTIST#*: }
ALBUM=${ALBUM#*: }

# Print out an IRC action
echo -e "\x01ACTION is listening to: $ARTIST - $TITLE [$ALBUM]\x01"

